 khởi tạo một tensor torch có khả năng theo dõi thay đổi theo 2 cách
 Cách 1: set requires_grad = True.
 Cách 2: Sử dụng inplace function.

In [35]:
# Cách 1
import torch

In [36]:
x = torch.ones(2, 2, requires_grad = True)
print(x)

y = x+2
print(y)

tensor([[1., 1.],
        [1., 1.]], requires_grad=True)
tensor([[3., 3.],
        [3., 3.]], grad_fn=<AddBackward0>)


In [37]:
print(y.grad_fn)

In [38]:
z = y * y * 3
out = z.mean()
print(z)
print(out)

tensor([[27., 27.],
        [27., 27.]], grad_fn=<MulBackward0>)
tensor(27., grad_fn=<MeanBackward0>)


In [25]:
# Cách 2
a = torch.ones(3, 3)
print(a)
print(a.requires_grad)
a.requires_grad_(True)
print(a.requires_grad)
b = (a*a).sum()
print(b)
print(b.grad_fn)

tensor([[1., 1., 1.],
        [1., 1., 1.],
        [1., 1., 1.]])
False
True
tensor(9., grad_fn=<SumBackward0>)


Gradients

In [39]:
out.backward()

Kết quả của gradient d(out)/dx sẽ được lưu trong phần tử x.grad.

d(out)/dx = d(3(x+2)^2 / 4)/dx = 3(x+2)/2 
Thay x = 1 ta được 4.5

In [40]:
print(x.grad)

tensor([[4.5000, 4.5000],
        [4.5000, 4.5000]])
