In [1]:
import numpy as np

## Create Numpy Array from Python Lists

In [2]:
np.array([1,2,3,4])

array([1, 2, 3, 4])

In [3]:
[1.1,2,3,4]

[1.1, 2, 3, 4]

In [4]:
np.array([1.1,2,3,4])

array([1.1, 2. , 3. , 4. ])

In [5]:
np.array([1,2,3,4], dtype='float32')

array([1., 2., 3., 4.], dtype=float32)

In [6]:
a1 = np.array([1,2,3,4])
type(a1)

numpy.ndarray

In [7]:
a2 = np.array([[1,2,3],
              [4,5,6]])
type(a2)

numpy.ndarray

**```shape```, ```dimension```, ```size```**

In [8]:
a2.shape

(2, 3)

In [9]:
a2.ndim

2

In [10]:
a2.size

6

## Create Numpy Arrays from Scratch

**```zeros```, ```ones```, ```full```, ```arange```, ```linspace```**

In [11]:
np.zeros([2,4])

array([[0., 0., 0., 0.],
       [0., 0., 0., 0.]])

In [12]:
np.zeros([2,4]).dtype

dtype('float64')

In [13]:
np.zeros([2,4], dtype = int)

array([[0, 0, 0, 0],
       [0, 0, 0, 0]])

In [14]:
np.ones([3,3], dtype = int)

array([[1, 1, 1],
       [1, 1, 1],
       [1, 1, 1]])

In [15]:
#Create an array filled with a linear sequence
#Starting at 0, ending at 20, stepping by 2
np.arange(0, 20, 2)

array([ 0,  2,  4,  6,  8, 10, 12, 14, 16, 18])

In [16]:
np.full((3,5), 17)

array([[17, 17, 17, 17, 17],
       [17, 17, 17, 17, 17],
       [17, 17, 17, 17, 17]])

In [17]:
# Create an array of five valies evenly spaced between 0 and 1
np.linspace(0,1,5)

array([0.  , 0.25, 0.5 , 0.75, 1.  ])

**```random```**

In [18]:
np.random.random((4,4))

array([[0.68384412, 0.67612542, 0.73310028, 0.95544085],
       [0.27493722, 0.07866781, 0.68326763, 0.58864684],
       [0.84225373, 0.99239291, 0.85377902, 0.59085415],
       [0.90101107, 0.7805329 , 0.86900482, 0.53109723]])

In [19]:
#Seed for reproducibility
np.random.seed(0)

np.random.random((4,4))

array([[0.5488135 , 0.71518937, 0.60276338, 0.54488318],
       [0.4236548 , 0.64589411, 0.43758721, 0.891773  ],
       [0.96366276, 0.38344152, 0.79172504, 0.52889492],
       [0.56804456, 0.92559664, 0.07103606, 0.0871293 ]])

In [20]:
np.random.rand(4,4)

array([[0.0202184 , 0.83261985, 0.77815675, 0.87001215],
       [0.97861834, 0.79915856, 0.46147936, 0.78052918],
       [0.11827443, 0.63992102, 0.14335329, 0.94466892],
       [0.52184832, 0.41466194, 0.26455561, 0.77423369]])

In [21]:
np.random.normal(0,1, (4,4))

array([[ 2.26975462, -1.45436567,  0.04575852, -0.18718385],
       [ 1.53277921,  1.46935877,  0.15494743,  0.37816252],
       [-0.88778575, -1.98079647, -0.34791215,  0.15634897],
       [ 1.23029068,  1.20237985, -0.38732682, -0.30230275]])

In [22]:
np.random.randint(0, 2, (3,3))

array([[0, 1, 1],
       [0, 1, 0],
       [0, 1, 0]])

## Array Indexing & Slicing
### One-dimensional subarray

In [23]:
x1 = np.random.randint(20, size = 6)
x1

array([ 6,  4, 15,  3, 12,  4])

In [24]:
x1[4], x1[0], x1[-1]

(12, 6, 4)

### Multi-dimensional array

In [25]:
x2 = np.random.randint(10, size = (3,4))
x2

array([[4, 8, 4, 3],
       [7, 5, 5, 0],
       [1, 5, 9, 3]])

In [26]:
x2[0,0], x2[1,1], x2[2,3]

(4, 5, 3)

### Slicing

In [27]:
x1[2:4]

array([15,  3])

In [28]:
x1[::2]

array([ 6, 15, 12])

In [29]:
x2[:,1], x2[2,:]

(array([8, 5, 5]), array([1, 5, 9, 3]))

In [30]:
x2[1:3,1:3]

array([[5, 5],
       [5, 9]])

## Reshaping of Arrays & Transpose

In [31]:
grid = np.arange(1,10)
grid.shape

(9,)

In [32]:
grid.reshape(3,3)

array([[1, 2, 3],
       [4, 5, 6],
       [7, 8, 9]])

In [33]:
x = np.array([1,2,3])
x.shape

(3,)

In [34]:
x.reshape((1,3)).shape

(1, 3)

In [35]:
x = np.array([[1.,2.],[3.,4.]])
x

array([[1., 2.],
       [3., 4.]])

In [36]:
x.T

array([[1., 3.],
       [2., 4.]])

## Array Concatenation & Splitting

In [37]:
x = np.array([1,2,3])
y = np.array([4,5,6])

In [38]:
np.concatenate((x,y))

array([1, 2, 3, 4, 5, 6])

In [39]:
grid = np.array([[1,2,3], [4,5,6]])
grid

array([[1, 2, 3],
       [4, 5, 6]])

In [40]:
np.concatenate((grid, grid))

array([[1, 2, 3],
       [4, 5, 6],
       [1, 2, 3],
       [4, 5, 6]])

In [41]:
np.concatenate((grid, grid),axis = 1)

array([[1, 2, 3, 1, 2, 3],
       [4, 5, 6, 4, 5, 6]])

**```vstack```, ```hstack```**

In [42]:
x = np.array([1,2,3])

grid = np.array([[9,8,7], [6,5,4]])

In [43]:
np.vstack((x,grid))

array([[1, 2, 3],
       [9, 8, 7],
       [6, 5, 4]])

In [44]:
y = np.array([[99], [99]])

np.hstack((y, grid))

array([[99,  9,  8,  7],
       [99,  6,  5,  4]])

## Splitting of arrays

In [45]:
x = np.array([1,2,3,66,99,3,2,1])

In [46]:
x1, x2, x3 = np.split(x,[3,5])

In [47]:
x1

array([1, 2, 3])

In [48]:
x2

array([66, 99])

In [49]:
x3

array([3, 2, 1])

## Broadcasting and Vectorized operations

Broadcasting is simply a set of rules for applying binary ufuncs on arrays of different sizes.

In [50]:
a = np.arange(3)
a

array([0, 1, 2])

In [51]:
a + 5 #Broadcasting

array([5, 6, 7])

In [52]:
b = np.ones((3,3), dtype = 'int')
b

array([[1, 1, 1],
       [1, 1, 1],
       [1, 1, 1]])

In [53]:
b+a

array([[1, 2, 3],
       [1, 2, 3],
       [1, 2, 3]])

## Manipulating & Comparing Arrays

### Aggregation
Aggregation = performing the same operation on a number of things

In [54]:
massive_array = np.random.random(10000)
massive_array.shape

(10000,)

In [55]:
%timeit sum(massive_array) #Python built-in function sum()
%timeit np.sum(massive_array) #Numpy sum

392 µs ± 6.35 µs per loop (mean ± std. dev. of 7 runs, 1,000 loops each)
3.07 µs ± 74.2 ns per loop (mean ± std. dev. of 7 runs, 100,000 loops each)


**```max```, ```min```, ```mean```, ```median```**

In [56]:
np.mean(massive_array)

0.49661190296401375

In [57]:
np.median(massive_array)

0.4934523135353668

In [58]:
np.max(massive_array)

0.9999779517807228

In [59]:
np.min(massive_array)

7.2449638492178e-05

## Statistics

#### Standard Deviation (độ lệch chuẩn) : ```np.std```, Variation (phương sai): ```np.var```

In [60]:
dog_height = [600,470,170,430,300]
dog_height = np.array(dog_height)

np.std(dog_height)

147.32277488562318

In [61]:
np.var(dog_height)

21704.0

In [62]:
np.sqrt(np.var(dog_height))

147.32277488562318

## Sorting Arrays
**```np.sort```** uses an quicksort algorithm

In [63]:
x = np.array([2,1,4,3,5])
np.sort(x)

array([1, 2, 3, 4, 5])

In [64]:
#A related function is argsort, which instead returns the indices of the sorted elements:
np.argsort(x)

array([1, 0, 3, 2, 4])

### Sorting along rows and columns
Numpy's sorting algorithms is the ability to sort along specific rows or columns of a multidimensional array using the axis argument

In [65]:
np.random.seed(42)

MatA = np.random.randint(0,10,size=(4,6))
MatA

array([[6, 3, 7, 4, 6, 9],
       [2, 6, 7, 4, 3, 7],
       [7, 2, 5, 4, 1, 7],
       [5, 1, 4, 0, 9, 5]])

In [66]:
np.sort(MatA)

array([[3, 4, 6, 6, 7, 9],
       [2, 3, 4, 6, 7, 7],
       [1, 2, 4, 5, 7, 7],
       [0, 1, 4, 5, 5, 9]])

In [67]:
np.sort(MatA, axis = 0)

array([[2, 1, 4, 0, 1, 5],
       [5, 2, 5, 4, 3, 7],
       [6, 3, 7, 4, 6, 7],
       [7, 6, 7, 4, 9, 9]])

In [68]:
np.sort(MatA, axis = 1)

array([[3, 4, 6, 6, 7, 9],
       [2, 3, 4, 6, 7, 7],
       [1, 2, 4, 5, 7, 7],
       [0, 1, 4, 5, 5, 9]])

## Linear Algebra

In [69]:
A = np.array([[1,2,3], [4,5,6], [7,8,9]])

In [70]:
B = np.array([[6,5], [4,3], [2,1]])

In [71]:
#Dot product A.B
A.dot(B)

array([[20, 14],
       [56, 41],
       [92, 68]])

In [72]:
A @ B

array([[20, 14],
       [56, 41],
       [92, 68]])

In [73]:
B.T @ A

array([[36, 48, 60],
       [24, 33, 42]])