In [16]:
import torch

In [17]:

x = torch.randn(3, 3)
print(x)
y = torch.ones(3, 3)
print(y)
print(y[1,1].item())
print(y.size())
print(y.view(9))

tensor([[-0.2936,  0.3655,  0.5549],
        [ 1.6178,  1.5282,  0.1978],
        [-0.7928, -1.6859,  1.5326]])
tensor([[1., 1., 1.],
        [1., 1., 1.],
        [1., 1., 1.]])
1.0
torch.Size([3, 3])
tensor([1., 1., 1., 1., 1., 1., 1., 1., 1.])


In [27]:
#phép cộng
print(x+y)
print(torch.add(x, y))

z = torch.empty(3,3)
torch.add(x, y, out = z)
print(z)

tensor([[ 0.7064,  1.3655,  1.5549],
        [ 2.6178,  2.5282,  1.1978],
        [ 0.2072, -0.6859,  2.5326]])
tensor([[ 0.7064,  1.3655,  1.5549],
        [ 2.6178,  2.5282,  1.1978],
        [ 0.2072, -0.6859,  2.5326]])
tensor([[ 0.7064,  1.3655,  1.5549],
        [ 2.6178,  2.5282,  1.1978],
        [ 0.2072, -0.6859,  2.5326]])


In [29]:
z = y
z.add_(x)
print(z)


tensor([[ 0.7064,  1.3655,  1.5549],
        [ 2.6178,  2.5282,  1.1978],
        [ 0.2072, -0.6859,  2.5326]])


In [32]:
print(x)
print(x[:, 1])
print(x[1, :])

tensor([[-0.2936,  0.3655,  0.5549],
        [ 1.6178,  1.5282,  0.1978],
        [-0.7928, -1.6859,  1.5326]])
tensor([ 0.3655,  1.5282, -1.6859])
tensor([1.6178, 1.5282, 0.1978])


In [44]:
x = torch.randn(4, 8)
y = x.view(4*8)
z = x.view(-1, 8) # Giá trị -1 cho biết kích thước của chiều này được tính theo các chiều còn lại

print(x.size(), y.size(), z.size())

torch.Size([4, 8]) torch.Size([32]) torch.Size([4, 8])


In [62]:
x = torch.tensor([1.5])
print(x)
i = x.item()
print(i)

tensor([1.5000])
1.5
