In [29]:
import torch

In [30]:
# Khởi tạo một ma trận rỗng
x = torch.empty(5, 3)
print(x)

tensor([[ 2.8026e-45,  0.0000e+00, -8.0712e-05],
        [ 1.2612e-42,  4.1929e-28,  4.5914e-41],
        [ 1.6816e-44,  0.0000e+00,  0.0000e+00],
        [ 0.0000e+00,  1.4026e-41,  0.0000e+00],
        [ 4.1929e-28,  4.5914e-41,  1.6816e-44]])


In [31]:
# Khởi tạo một ma trận ngẫu nhiên
x = torch.rand(5, 3)
print(x)

tensor([[0.4079, 0.1133, 0.8180],
        [0.3125, 0.2600, 0.5586],
        [0.7616, 0.4479, 0.4192],
        [0.3218, 0.1231, 0.0143],
        [0.3561, 0.4941, 0.3766]])


In [32]:
# Khởi tạo ma trận 0 với data type là long
x = torch.zeros(5, 3, dtype = torch.long)
print(x)

tensor([[0, 0, 0],
        [0, 0, 0],
        [0, 0, 0],
        [0, 0, 0],
        [0, 0, 0]])


In [33]:
# Khởi tạo ma trận từ list
x = torch.tensor([[5, 3.5],[2,3]])
print(x)

tensor([[5.0000, 3.5000],
        [2.0000, 3.0000]])


In [34]:
# Khởi tạo ma trận có các thuộc tính tương tự như của một ma trận sẵn có. 
#Chẳng hạn như shape. Trừ khi thuộc tính mới được đưa vào override thuộc tính cũ.
x = x.new_ones(5, 3, dtype = torch.double)
print(x)

tensor([[1., 1., 1.],
        [1., 1., 1.],
        [1., 1., 1.],
        [1., 1., 1.],
        [1., 1., 1.]], dtype=torch.float64)


In [35]:
x = torch.randn_like(x, dtype = torch.float) #override dtype
# Ma trận mới được khởi tạo ngẫu nhiên có shape tương tự như ma trận cũ, dtype được override.
print(x)

tensor([[ 0.4218, -0.7123,  0.0723],
        [ 0.4536, -0.0409, -0.7795],
        [-0.1065, -1.0231,  1.3410],
        [ 0.2023, -0.6570,  1.0741],
        [ 0.4548, -0.8773, -0.5209]])
